<%@ page language="java"  pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<link href="<c:url value='/temple/themes/default/style.css'/>" rel="stylesheet" type="text/css" media="screen"/>
<link href="<c:url value='/temple/themes/silver/style.css'/>" rel="stylesheet" type="text/css" media="screen"/>
<link href="<c:url value='/temple/themes/css/core.css'/>" rel="stylesheet" type="text/css" media="screen"/>
<link href="<c:url value='/temple/themes/css/print.css'/>" rel="stylesheet" type="text/css" media="print"/>
<link href="<c:url value='/temple/uploadify/css/uploadify.css'/>" rel="stylesheet" type="text/css" media="screen"/>
<!--[if IE]>
<link href="<c:url value='/temple/themes/css/ieHack.css'/>" rel="stylesheet" type="text/css" media="screen"/>
<![endif]-->
<script src="<c:url value='/temple/js/speedup.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/jquery-1.7.1.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/jquery.cookie.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/jquery.validate.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/jquery.bgiframe.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/xheditor/xheditor-1.1.12-zh-cn.min.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/uploadify/scripts/swfobject.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/uploadify/scripts/jquery.uploadify.v2.1.0.js'/>" type="text/javascript"></script>

<script src="<c:url value='/temple/js/dwz.core.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.util.date.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.validate.method.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.regional.zh.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.barDrag.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.drag.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.tree.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.accordion.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.ui.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.theme.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.switchEnv.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.alertMsg.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.contextmenu.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.navTab.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.tab.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.resize.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.dialog.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.dialogDrag.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.sortDrag.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.cssTable.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.stable.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.taskBar.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.ajax.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.pagination.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.database.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.datepicker.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.effects.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.panel.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.checkbox.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.history.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.combox.js'/>" type="text/javascript"></script>
<script src="<c:url value='/temple/js/dwz.print.js'/>" type="text/javascript"></script>